BUILD: mworker: fix ignoring return value of ‘read’
Fix read return value unused result.

src/haproxy.c: In function ‘main’:
src/haproxy.c:3630:17: error: ignoring return value of ‘read’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
 3630 |                 read(sock_pair[1], &c, 1);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~

Must be backported where d7f6819 is backported.