IMPORT: slz: prevent build compilation error due to unused __slz_make_crc_table()
In __slz_common_initialize(), __slz_make_crc_table() was not
systematically called (ie: when __ARM_FEATURE_CRC32 is defined the
crc32_fast[] table is not used). However since the function is defined
as static, AND its content is already guarded by the same
__ARM_FEATURE_CRC32, we actually need to call always call the function,
else we could face a compilation warning on some systems such as:

src/slz_common.c:258:20: error: unused function '__slz_make_crc_table' [-Werror,-Wunused-function]
  258 | static inline void __slz_make_crc_table(void)

This is libslz upstream commit 7d8744a64ca78ff4ac66bff4f6839d416537f312