BUILD: fd: unshare is not available on NetBSD
Define HA_HAVE_UNSHARE which tests CLONE_FILES with an exception on
NetBSD which has the CLONE_FILES define for clone() but doesn't provide
unshare().

  src/thread.c: In function ‘start_extra_tgroup_threads’:
  src/thread.c:244:21: error: implicit declaration of function ‘unshare’ [-Werror=implicit-function-declaration]
    244 |                 if (unshare(CLONE_FILES) != 0) {
        |                     ^~~~~~~

No backport needed.