BUILD: solaris: fix redefinition of queue struct
Compilation on solaris fails because the name 'queue' is reserved:

> include/haproxy/queue-t.h:43:8: error: redefinition of ‘struct queue’

This patch redefines 'queue' as '_queue' which fixes compilation for now.

Future plan: rename 'queue' in code base so define can be removed again.

Backporting: 2.9, 2.8